# Generated by Django 5.0.14 on 2026-06-30 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('wompi', 'Wompi'), ('paypal', 'PayPal')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('logo_url', models.URLField(blank=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Metodo de Pago',
                'verbose_name_plural': 'Metodos de Pago',
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='pendiente', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('payer_email', models.EmailField(blank=True, max_length=255)),
                ('payment_data', models.JSONField(blank=True, default=dict)),
                ('creada_en', models.DateTimeField(auto_now_add=True, db_column='creada_en')),
                ('pagada_en', models.DateTimeField(blank=True, db_column='pagada_en', null=True)),
                ('pdf_generado', models.BooleanField(db_column='pdf_generado', default=False)),
                ('movimiento', models.ForeignKey(blank=True, db_column='id_movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.movimiento')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(db_column='id_metodo_pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.metodopago')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(db_column='precio_unitario', decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.factura')),
                ('producto', models.ForeignKey(db_column='id_producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Item de Factura',
                'verbose_name_plural': 'Items de Factura',
                'db_table': 'item_factura',
            },
        ),
    ]
