# Generated by Django 6.0.6 on 2026-06-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='pagada_en',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='payment_data',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago_nombre',
            field=models.CharField(blank=True, db_column='metodo_pago_nombre', max_length=60),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('emitida', 'Emitida'), ('cancelada', 'Cancelada')], default='emitida', max_length=20),
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
    ]
