# Generated by Django 4.2.13 on 2026-03-10 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_remove_producto_agricultor_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('area_hectareas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_siembra', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cosechado', 'Cosechado'), ('abandonado', 'Abandonado')], default='activo', max_length=50)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsoProductoCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_aplicacion', models.DateField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.AddField(
            model_name='cultivo',
            name='productos_utilizados',
            field=models.ManyToManyField(through='cultivos.UsoProductoCultivo', to='inventario.producto'),
        ),
    ]
