# Generated by Django 4.2.13 on 2026-03-10 20:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='HistorialProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField(db_index=True)),
                ('usuario_id', models.IntegerField(null=True)),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('eliminacion', 'Eliminación')], max_length=20)),
                ('campo_modificado', models.CharField(blank=True, max_length=50)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=5)),
                ('agricultor_id', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('eliminado', 'Eliminado')], default='pendiente', max_length=20)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('eliminado_por_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
