# Generated by Django 4.2.13 on 2026-03-10 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='agricultor_id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='eliminado_por_id',
        ),
        migrations.AddField(
            model_name='producto',
            name='agricultor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_eliminados', to=settings.AUTH_USER_MODEL),
        ),
    ]
