# Generated by Django 6.0.2 on 2026-02-24 22:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Termino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(default='Términos y Condiciones', max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Término y Condición',
                'verbose_name_plural': 'Términos y Condiciones',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='AceptacionTermino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_aceptacion', models.DateTimeField(auto_now_add=True)),
                ('ip_aceptacion', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('termino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.termino')),
            ],
            options={
                'unique_together': {('usuario', 'termino')},
            },
        ),
    ]
