# Generated by Django 4.2.13 on 2026-03-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('agricultor', 'Agricultor'), ('cliente', 'Cliente'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
