# Generated by Django 4.2.13 on 2026-05-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_userprofile_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Administrador')], default='usuario', max_length=20),
        ),
    ]
