# Generated by Django 4.2.11 on 2026-04-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_solicitudcompra_detallesolicitudcompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcompra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vendido', 'Vendido')], default='pendiente', max_length=20),
        ),
    ]
